-- Seed the 50 most-frequent vocabulary cards (frequency_rank 1-50, aligned
-- with id 1-50) plus their English translations, so a fresh database has
-- real starter content. INSERT OR IGNORE is a no-op against production,
-- which already has these exact rows/ids.

INSERT OR IGNORE INTO cards
    (id, krdict_id, word, definition, hanja, hanja_eum, frequency_rank, audio_path, grammar_pattern_id, pos_id, origin_type_id, grade_id)
VALUES
    (1,62835,'것','정확히 가리키는 대상이 정해지지 않은 사물이나 사실.',NULL,NULL,1,NULL,NULL,5,1,1),
    (2,73277,'하다','어떤 행동이나 동작, 활동 등을 행하다.',NULL,NULL,2,NULL,NULL,1,1,1),
    (3,68797,'있다','사람, 동물, 물체 등이 존재하는 상태이다.',NULL,NULL,4,NULL,NULL,3,1,1),
    (4,89858,'되다','새로운 신분이나 지위를 가지다.',NULL,NULL,5,NULL,NULL,1,1,1),
    (5,15615,'수','어떤 일을 할 만한 능력이나 어떤 일이 일어날 가능성.',NULL,NULL,6,NULL,NULL,5,1,1),
    (6,60931,'나','말하는 사람이 친구나 아랫사람에게 자기를 가리키는 말.',NULL,NULL,8,NULL,NULL,6,1,1),
    (7,89917,'없다','사람이나 사물 등이 실제로 존재하지 않는 상태이다.',NULL,NULL,10,NULL,NULL,3,1,1),
    (8,58161,'사람','생각할 수 있으며 언어와 도구를 만들어 사용하고 사회를 이루어 사는 존재.',NULL,NULL,12,NULL,NULL,2,1,1),
    (9,17182,'우리','말하는 사람이 자기와 듣는 사람 또는 이를 포함한 여러 사람들을 가리키는 말.',NULL,NULL,13,NULL,NULL,6,1,1),
    (10,62250,'그','말하는 사람과 듣는 사람이 아닌 사람을 가리키는 말.',NULL,NULL,15,NULL,NULL,6,1,1),
    (11,26878,'아니다','어떤 사실이나 내용을 부정하는 뜻을 나타내는 말.',NULL,NULL,16,NULL,NULL,3,1,1),
    (12,61190,'보다','눈으로 대상의 존재나 겉모습을 알다.',NULL,NULL,17,NULL,NULL,1,1,1),
    (13,74123,'때','시간의 어떤 순간이나 부분.',NULL,NULL,19,NULL,NULL,2,1,1),
    (14,62331,'거','어떤 사물이나 현상, 또는 사실.',NULL,NULL,20,NULL,NULL,5,1,1),
    (15,62076,'같다','서로 다르지 않다.',NULL,NULL,22,NULL,NULL,3,1,1),
    (16,27500,'가다','한 곳에서 다른 곳으로 장소를 이동하다.',NULL,NULL,25,NULL,NULL,1,1,1),
    (17,26823,'년','한 해를 세는 단위.','年','년',26,NULL,NULL,5,2,1),
    (18,73278,'한','하나의.',NULL,NULL,27,NULL,NULL,9,1,1),
    (19,27260,'말','생각이나 느낌을 표현하고 전달하는 사람의 소리.',NULL,NULL,28,NULL,NULL,2,1,1),
    (20,91895,'일','무엇을 이루려고 몸이나 정신을 사용하는 활동. 또는 그 활동의 대상.',NULL,NULL,29,NULL,NULL,2,1,1),
    (21,64555,'때문','어떤 일의 원인이나 이유.',NULL,NULL,31,NULL,NULL,5,1,1),
    (22,62103,'말하다','어떤 사실이나 자신의 생각 또는 느낌을 말로 나타내다.',NULL,NULL,32,NULL,NULL,1,1,1),
    (23,62263,'그러나','앞의 내용과 뒤의 내용이 서로 반대될 때 쓰는 말.',NULL,NULL,34,NULL,NULL,4,1,1),
    (24,69514,'오다','무엇이 다른 곳에서 이곳으로 움직이다.',NULL,NULL,35,NULL,NULL,1,1,1),
    (25,89445,'알다','교육이나 경험, 생각 등을 통해 사물이나 상황에 대한 정보 또는 지식을 갖추다.',NULL,NULL,36,NULL,NULL,1,1,1),
    (26,58145,'씨','그 사람을 높여 부르거나 이르는 말.','氏',NULL,37,NULL,NULL,5,1,1),
    (27,61178,'그렇다','상태, 모양, 성질 등이 그와 같다.',NULL,NULL,38,NULL,NULL,3,1,1),
    (28,66586,'크다','길이, 넓이, 높이, 부피 등이 보통 정도를 넘다.',NULL,NULL,39,NULL,1,3,1,1),
    (29,51887,'또','어떤 일이나 행동이 다시.',NULL,NULL,40,NULL,NULL,4,1,1),
    (30,69295,'많다','수나 양, 정도 등이 일정한 기준을 넘다.',NULL,NULL,43,NULL,NULL,3,1,1),
    (31,71372,'안','부정이나 반대의 뜻을 나타내는 말.',NULL,NULL,44,NULL,NULL,4,1,1),
    (32,79033,'좋다','어떤 것의 성질이나 내용 등이 훌륭하여 만족할 만하다.',NULL,NULL,45,NULL,NULL,3,1,1),
    (33,26829,'더','보태어 계속해서.',NULL,NULL,46,NULL,NULL,4,1,1),
    (34,66636,'받다','다른 사람이 주거나 보내온 것을 가지다.',NULL,NULL,47,NULL,NULL,1,1,1),
    (35,31953,'그것','듣는 사람에게 가까이 있거나 듣는 사람이 생각하고 있는 것을 가리키는 말.',NULL,NULL,48,NULL,NULL,6,1,1),
    (36,71358,'집','사람이나 동물이 추위나 더위 등을 막고 그 속에 들어 살기 위해 지은 건물.',NULL,NULL,49,NULL,NULL,2,1,1),
    (37,62233,'나오다','안에서 밖으로 오다.',NULL,NULL,50,NULL,NULL,1,1,1),
    (38,62240,'그리고','앞의 내용에 이어 뒤의 내용을 단순히 나열할 때 쓰는 말.',NULL,NULL,52,NULL,NULL,4,1,1),
    (39,66246,'문제','답을 요구하는 물음.','問題','문제',53,NULL,NULL,2,2,1),
    (40,60341,'그런','상태, 모양, 성질 등이 그러한.',NULL,NULL,54,NULL,NULL,9,1,1),
    (41,69579,'살다','생명을 지니고 있다.',NULL,NULL,55,NULL,NULL,1,1,1),
    (42,44506,'저','말하는 사람이 듣는 사람에게 자신을 낮추어 가리키는 말.',NULL,NULL,56,NULL,NULL,6,1,1),
    (43,66376,'생각하다','사람이 머리를 써서 판단하거나 인식하다.',NULL,NULL,58,NULL,NULL,1,1,1),
    (44,29712,'모르다','사람이나 사물, 사실 등을 알지 못하거나 이해하지 못하다.',NULL,NULL,59,NULL,NULL,1,1,1),
    (45,71278,'속','거죽이나 껍질로 싸인 물체의 안쪽 부분.',NULL,NULL,60,NULL,NULL,2,1,1),
    (46,60317,'만들다','힘과 기술을 써서 없던 것을 생기게 하다.',NULL,NULL,61,NULL,NULL,1,1,1),
    (47,71458,'두','둘의.',NULL,NULL,63,NULL,NULL,9,1,1),
    (48,88648,'앞','향하고 있는 쪽이나 곳.',NULL,NULL,64,NULL,NULL,2,1,1),
    (49,17185,'어떤','사람이나 사물의 특징, 내용, 성격, 성질, 모양 등이 무엇인지 물을 때 쓰는 말.',NULL,NULL,67,NULL,NULL,9,1,1),
    (50,58939,'잘','바르고 선하게.',NULL,NULL,68,NULL,NULL,4,1,1);

INSERT OR IGNORE INTO card_translations
    (id, card_id, language_tag, trans_word, trans_dfn)
VALUES
    (1,1,'en','thing','A bound noun used to refer to a thing or fact that is not specified or determind by someone.'),
    (2,2,'en','doing, studying','To perform a certain move, action, activity, etc.'),
    (3,3,'en','exist','A person, an animal, an object, etc., being in existence.'),
    (4,4,'en','became','To have a new status or position.'),
    (5,5,'en','can','A bound noun meaning the ability to do something or the possibility that a certain event occurs.'),
    (6,6,'en','I (casual)','A pronoun used to indicate oneself to a friend or a younger person.'),
    (7,7,'en','no (don''t exist)','(for a person or thing to be) Not existent in reality.'),
    (8,8,'en','Humans','A being that is capable of thinking, makes and uses languages and tools and lives by forming a society with others.'),
    (9,9,'en','us','A pronoun used when the speaker refers to himself/herself and the listener or listeners, or a group of people including the speaker and listener or listeners.'),
    (10,10,'en','him','A pronoun used to indicate people who are not the speaker or listener.'),
    (11,11,'en','not','Used to negate a fact or statement.'),
    (12,12,'en','saw','To perceive with eyes the existence or appearance of an object.'),
    (13,13,'en','anytime','A certain moment or part of time.'),
    (14,14,'en','one','A bound noun used to refer to a certain thing or phenomenon, or fact.'),
    (15,15,'en','same','Not different from each other.'),
    (16,16,'en','going','To move from one place to another place.'),
    (17,17,'en','years','A bound noun that serves as a unit for counting the number of years.'),
    (18,18,'en','one','One.'),
    (19,19,'en','words','Human voice through which thoughts or feelings are expressed and conveyed.'),
    (20,20,'en','work','An activity that uses one''s body or mind in order to achieve something; the object of such an activity.'),
    (21,21,'en','because','A cause or reason for a certain incident.'),
    (22,22,'en','tell','To verbally present a fact or one''s thoughts or feelings.'),
    (23,23,'en','However','A word used to indicate that a statement is the opposite of the following statement.'),
    (24,24,'en','come','For something to move from another place to here.'),
    (25,25,'en','know','To have information or knowledge about an object or situation through education, experience, thoughts, etc.'),
    (26,26,'en','(polite name suffix used when addressing a person directly)','A bound noun used to address or call out to a certain person deferentially.'),
    (27,27,'en','such','A state, appearance, characteristic, etc. being as such.'),
    (28,28,'en','bigger','A length, width, height, volume, etc., exceeding an ordinary degree.'),
    (29,29,'en','again','In the manner of happening or behaving again.'),
    (30,30,'en','much','A number, amount, etc., exceeding a certain standard.'),
    (31,31,'en','not',replace('An adverb that has the meaning of negation or opposite. \n','\n',char(10))),
    (32,32,'en','good','Excellent and satisfactory in features and content.'),
    (33,33,'en','more','In a continuous addition.'),
    (34,34,'en','receive','To take something that someone else has given or sent.'),
    (35,35,'en','that','A pronoun used to indicate something close to the listener, or something the listener has in mind.'),
    (36,36,'en','nest/house','A structure built by a human or animal to serve as protection from cold, heat, etc., and as a place to live in.'),
    (37,37,'en','come','To come out.'),
    (38,38,'en','and','A word used to connect the preceding statement with the following one.'),
    (39,39,'en','questions','A question that demands an answer.'),
    (40,40,'en','such',replace('A state, appearance, characteristic, etc. being as such.\n\n','\n',char(10))),
    (41,41,'en','alive','To be alive.'),
    (42,42,'en','I','The humble form used by the speaker to refer to himself/herself for the purpose of showing humility to the listener.'),
    (43,43,'en','think','To judge or perceive something by using one''s brain.'),
    (44,44,'en','(doesn''t) know','To have no knowledge or understanding of a person, object or fact.'),
    (45,45,'en','inside','The inside part of an object that is covered with a coat or skin.'),
    (46,46,'en','made','To create something that did not exist, using one''s power or skill.'),
    (47,47,'en','two','Two'),
    (48,48,'en','in front','The direction or place one is facing.'),
    (49,49,'en','what kind of','A word used when asking what characteristic, content, personality, quality, shape, etc., a person or object has.'),
    (50,50,'en','well','Rightly and virtuously.');
