/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/cards/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_cards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Freeform partial-update body: any subset of `word`, `definition`, `pos`,
         *     `origin_type`, `hanja`, `hanja_eum`, `grade`, `trans_word`, `trans_dfn`,
         *     `sentence`, `sentence_translation`, `target`, `alternatives` (array),
         *     `speech_level`, `tense`, `grammar_pattern`. Absent keys are left
         *     untouched; explicit `null` clears a nullable column. Enum-backed fields
         *     are sent as slugs, resolved server-side to lookup-table row IDs.
         */
        patch: operations["edit_card"];
        trace?: never;
    };
    "/api/admin/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_invites"];
        put?: never;
        post: operations["generate_invites"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/invites/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_invite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/enum-lookups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_enum_lookups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_review_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/history-breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_history_breakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/history-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_history_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_next_card"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/optimize-fsrs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["optimize_fsrs"];
        delete: operations["reset_fsrs_parameters"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/suppressed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_suppressed_cards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submit_review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}/suppress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["suppress_card"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}/unsuppress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["unsuppress_card"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custom-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_custom_cards"];
        put?: never;
        post: operations["create_custom_card"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custom-cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_custom_card"];
        put?: never;
        post?: never;
        delete: operations["delete_custom_card"];
        options?: never;
        head?: never;
        patch: operations["update_custom_card"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["export_data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["import_data"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_settings"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponse: {
            is_admin: boolean;
            token: string;
            username: string;
        };
        BreakdownRow: {
            /** Format: double */
            accuracy: number;
            /** Format: int64 */
            correct: number;
            label: string;
            /** Format: int64 */
            reviews: number;
        };
        /**
         * @description The canonical card shape: a `cards` row joined with its English
         *     translation and primary example sentence. Shared verbatim by the review
         *     flow (`NextCardResponse`, below) and admin search (`admin::search_cards`)
         *     - previously two independently hand-declared structs that happened to
         *     agree on 14 of their fields, which is exactly the kind of duplication
         *     that drifts silently over time.
         */
        Card: {
            alternatives: string[];
            /** Format: int64 */
            card_id: number;
            definition?: string | null;
            grade?: string | null;
            grammar_pattern?: string | null;
            hanja?: string | null;
            hanja_eum?: string | null;
            origin_type?: string | null;
            pos?: string | null;
            sentence: string;
            sentence_translation: string;
            speech_level?: string | null;
            target: string;
            tense?: string | null;
            trans_dfn?: string | null;
            trans_word: string;
            word: string;
        };
        CardTranslationExport: {
            language_tag: string;
            trans_dfn?: string | null;
            trans_word: string;
        };
        CreateCustomCardRequest: {
            alternatives?: string[] | null;
            definition?: string | null;
            grade?: string | null;
            hanja?: string | null;
            hanja_eum?: string | null;
            origin_type?: string | null;
            pos?: string | null;
            sentence: string;
            sentence_translation: string;
            speech_level?: string | null;
            target: string;
            tense?: string | null;
            trans_dfn?: string | null;
            trans_word: string;
            word: string;
        };
        CreateCustomCardResponse: {
            /** Format: int64 */
            id: number;
            success: boolean;
        };
        CustomCard: {
            created_at: string;
            definition?: string | null;
            grade?: string | null;
            hanja?: string | null;
            hanja_eum?: string | null;
            /** Format: int64 */
            id: number;
            origin_type?: string | null;
            pos?: string | null;
            sentence: string;
            sentence_translation: string;
            speech_level?: string | null;
            target: string;
            tense?: string | null;
            trans_dfn?: string | null;
            trans_word: string;
            word: string;
        };
        CustomCardExport: {
            definition?: string | null;
            grade?: string | null;
            hanja?: string | null;
            hanja_eum?: string | null;
            origin_type?: string | null;
            pos?: string | null;
            sentences: components["schemas"]["SentenceExport"][];
            translations: components["schemas"]["CardTranslationExport"][];
            word: string;
        };
        DayHistory: {
            /** Format: int64 */
            correct: number;
            date: string;
            /** Format: int64 */
            percentage: number;
            /** Format: int64 */
            total: number;
        };
        EnumEntry: {
            endings?: string | null;
            label: string;
            /** Format: int64 */
            rank?: number | null;
            slug: string;
            tooltip?: string | null;
        };
        EnumLookups: {
            grade: components["schemas"]["EnumEntry"][];
            grammar_pattern: components["schemas"]["EnumEntry"][];
            origin_type: components["schemas"]["EnumEntry"][];
            pos: components["schemas"]["EnumEntry"][];
            speech_level: components["schemas"]["EnumEntry"][];
            tense: components["schemas"]["EnumEntry"][];
        };
        /**
         * @description Schema-only mirror of the `{"error": "..."}` envelope every error
         *     response uses (built ad hoc via `serde_json::json!` in
         *     `AppError::into_response`, not actually constructed from this struct) -
         *     exists purely so `#[utoipa::path]` annotations have something to point
         *     error responses at.
         */
        ErrorResponse: {
            error: string;
        };
        ExportData: {
            custom_cards: components["schemas"]["CustomCardExport"][];
            exported_at: string;
            review_history: components["schemas"]["ReviewHistoryExport"][];
            settings: components["schemas"]["UserSettingsExport"];
            suspended_cards: number[];
            version: string;
        };
        GenerateInvitesRequest: {
            count: number;
        };
        GenerateInvitesResponse: {
            codes: components["schemas"]["GeneratedInvite"][];
        };
        GeneratedInvite: {
            code: string;
        };
        HanjaHint: {
            hanja: string;
            hanja_eum?: string | null;
            trans_word?: string | null;
        };
        HistoryBreakdownResponse: {
            by_origin: components["schemas"]["BreakdownRow"][];
            by_pos: components["schemas"]["BreakdownRow"][];
        };
        HistorySummary: {
            /** Format: double */
            avg_reviews_per_day: number;
            /** Format: int64 */
            cards_learning: number;
            /** Format: int64 */
            cards_relearning: number;
            /** Format: int64 */
            cards_review: number;
            /** Format: int64 */
            cards_unseen: number;
            /** Format: int64 */
            current_streak: number;
            first_review_date?: string | null;
            /** Format: int64 */
            longest_streak: number;
            /** Format: double */
            total_accuracy: number;
            /** Format: int64 */
            total_cards_reviewed: number;
            /** Format: int64 */
            total_reviews: number;
        };
        ImportDataRequest: {
            data: components["schemas"]["ExportData"];
            overwrite: boolean;
        };
        ImportDataResponse: {
            message: string;
            stats: components["schemas"]["ImportStats"];
            success: boolean;
        };
        ImportStats: {
            card_states_derived: number;
            custom_cards_imported: number;
            reviews_imported: number;
            suspended_cards_imported: number;
        };
        InflectionHintExport: {
            speech_level?: string | null;
            tense?: string | null;
        };
        InviteCode: {
            code: string;
            created_at: string;
            used_at?: string | null;
            used_by_username?: string | null;
        };
        ListCustomCardsResponse: {
            cards: components["schemas"]["CustomCard"][];
        };
        ListInvitesResponse: {
            codes: components["schemas"]["InviteCode"][];
        };
        LoginRequest: {
            password: string;
            username: string;
        };
        NextCardEnvelope: {
            card?: null | components["schemas"]["NextCardResponse"];
            next_due_at?: string | null;
        };
        NextCardResponse: components["schemas"]["Card"] & {
            /** Format: double */
            difficulty?: number | null;
            /** Format: int64 */
            guess_count: number;
            hanja_hints: components["schemas"]["HanjaHint"][];
            /** Format: int64 */
            wrong_guess_count: number;
        };
        OptimizeFsrsResponse: {
            parameters: number[];
            review_count: number;
            success: boolean;
        };
        ReviewHistoryExport: {
            /** Format: int64 */
            card_id: number;
            /** Format: double */
            difficulty?: number | null;
            /** Format: double */
            elapsed_days?: number | null;
            rating: string;
            reviewed_at: string;
            /** Format: double */
            scheduled_days?: number | null;
            /** Format: double */
            stability?: number | null;
            state?: string | null;
        };
        ReviewHistoryResponse: {
            days: components["schemas"]["DayHistory"][];
        };
        ReviewRequest: {
            /**
             * Format: int32
             * @description FSRS rating: 1 = Again, 2 = Hard, 3 = Good, 4 = Easy (UI only sends 1 or 3)
             */
            rating: number;
        };
        ReviewResponse: {
            success: boolean;
        };
        SearchCardsResponse: {
            cards: components["schemas"]["Card"][];
        };
        SentenceExport: {
            alternatives?: string[];
            inflection_hint?: null | components["schemas"]["InflectionHintExport"];
            target: string;
            text: string;
            translation?: string | null;
        };
        SignupRequest: {
            invite_code: string;
            password: string;
            username: string;
        };
        StatsResponse: {
            /** Format: int64 */
            correct_today: number;
            /** Format: int64 */
            due_count: number;
            /** Format: int64 */
            new_count: number;
            /** Format: int64 */
            new_today_count: number;
            next_due_at?: string | null;
            /** Format: int64 */
            percentage?: number | null;
            /** Format: int64 */
            reviews_today: number;
        };
        SuppressedCard: {
            /** Format: int64 */
            card_id: number;
            grade?: string | null;
            pos?: string | null;
            sentence: string;
            sentence_translation: string;
            trans_word: string;
            word: string;
        };
        SuppressedCardsResponse: {
            cards: components["schemas"]["SuppressedCard"][];
        };
        UpdateCustomCardRequest: {
            alternatives?: string[] | null;
            definition?: string | null;
            grade?: string | null;
            hanja?: string | null;
            hanja_eum?: string | null;
            origin_type?: string | null;
            pos?: string | null;
            sentence?: string | null;
            sentence_translation?: string | null;
            speech_level?: string | null;
            target?: string | null;
            tense?: string | null;
            trans_dfn?: string | null;
            trans_word?: string | null;
            word?: string | null;
        };
        UpdateCustomCardResponse: {
            success: boolean;
        };
        UpdateSettingsRequest: {
            /** Format: int64 */
            auto_progress_delay?: number | null;
            auto_progress_on_correct?: boolean | null;
            /** Format: int64 */
            daily_new_card_limit?: number | null;
            /** Format: int64 */
            day_boundary_hour?: number | null;
            /** Format: double */
            desired_retention?: number | null;
            history_colored_dots?: boolean | null;
            history_colorized_area?: boolean | null;
            history_threshold_lines?: boolean | null;
            /** Format: int64 */
            red_threshold?: number | null;
            show_percentage?: boolean | null;
            /** Format: int64 */
            yellow_threshold?: number | null;
        };
        UpdateSettingsResponse: {
            success: boolean;
        };
        UserProfile: {
            username: string;
        };
        UserSettings: {
            /** Format: int64 */
            auto_progress_delay: number;
            auto_progress_on_correct: boolean;
            /** Format: int64 */
            daily_new_card_limit: number;
            /** Format: int64 */
            day_boundary_hour: number;
            /** Format: double */
            desired_retention: number;
            has_fsrs_parameters: boolean;
            history_colored_dots: boolean;
            history_colorized_area: boolean;
            history_threshold_lines: boolean;
            /** Format: int64 */
            red_threshold: number;
            show_percentage: boolean;
            /** Format: int64 */
            yellow_threshold: number;
        };
        UserSettingsExport: {
            /** Format: int64 */
            auto_progress_delay: number;
            auto_progress_on_correct: boolean;
            /** Format: int64 */
            daily_new_card_limit: number;
            /** Format: int64 */
            day_boundary_hour: number;
            /** Format: double */
            desired_retention: number;
            fsrs_parameters?: string | null;
            history_colored_dots: boolean;
            history_colorized_area: boolean;
            history_threshold_lines: boolean;
            /** Format: int64 */
            red_threshold: number;
            show_percentage: boolean;
            /** Format: int64 */
            yellow_threshold: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_cards: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cards matching a substring search over sentence targets (capped at 50) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchCardsResponse"];
                };
            };
            /** @description Malformed query string */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Valid JWT but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    edit_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                card_id: number;
            };
            cookie?: never;
        };
        /** @description Partial card edit, see handler doc comment for accepted fields */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Card updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Body isn't a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Valid JWT but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Card doesn't exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_invites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All invite codes, used and unused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListInvitesResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Valid JWT but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generate_invites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateInvitesRequest"];
            };
        };
        responses: {
            /** @description Invite codes generated (capped at 100 per request) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateInvitesResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Valid JWT but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invite code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite code deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Valid JWT but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Code doesn't exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid/used invite code, or malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Username already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_enum_lookups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lookup-table values for dropdowns/enum displays */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnumLookups"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_review_history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-day review history for a rolling window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewHistoryResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_history_breakdown: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accuracy broken down by part-of-speech and origin type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryBreakdownResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_history_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate review history summary + streaks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistorySummary"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_next_card: {
        parameters: {
            query?: {
                exclude?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next due/new card, or null if none due */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextCardEnvelope"];
                };
            };
            /** @description Malformed query string */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    optimize_fsrs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FSRS parameters optimized from full review history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizeFsrsResponse"];
                };
            };
            /** @description No/insufficient review history to optimize from */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reset_fsrs_parameters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FSRS parameters reset to library defaults */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status-bar summary stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_suppressed_cards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All suspended cards for the user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuppressedCardsResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    submit_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Review recorded, FSRS state updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Invalid rating or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    suppress_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card suspended from review rotation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    unsuppress_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card un-suspended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_custom_cards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All custom cards owned by the caller */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCustomCardsResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_custom_card: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomCardRequest"];
            };
        };
        responses: {
            /** @description Custom card created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCustomCardResponse"];
                };
            };
            /** @description Empty required field or target not in sentence */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_custom_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Custom card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single custom card */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomCard"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found, or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_custom_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Custom card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom card deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found, or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_custom_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Custom card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomCardRequest"];
            };
        };
        responses: {
            /** @description Custom card updated (partial update) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateCustomCardResponse"];
                };
            };
            /** @description Empty field or target not in sentence */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found, or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    export_data: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full data export: settings, review history, suspended cards, custom cards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportData"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    import_data: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportDataRequest"];
            };
        };
        responses: {
            /** @description Data imported (card_states derived from imported review_history) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDataResponse"];
                };
            };
            /** @description Unsupported export version or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user's profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user settings (row lazily created on first access) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description Settings updated (partial update, only provided fields written) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateSettingsResponse"];
                };
            };
            /** @description Out-of-range value or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
