/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/cards/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_cards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["edit_card"];
        trace?: never;
    };
    "/api/admin/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_invites"];
        put?: never;
        post: operations["generate_invites"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/invites/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_invite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/field-values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_field_values"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_next_card"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/optimize-fsrs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["optimize_fsrs"];
        delete: operations["reset_fsrs_parameters"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/suppressed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_suppressed_cards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["check_answer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["comment_on_card"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}/suppress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["suppress_card"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}/unsuppress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["unsuppress_card"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custom-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_custom_cards"];
        put?: never;
        post: operations["create_custom_card"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custom-cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_custom_card"];
        put?: never;
        post?: never;
        delete: operations["delete_custom_card"];
        options?: never;
        head?: never;
        patch: operations["update_custom_card"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["export_data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["import_data"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_settings"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminUserSummary: {
            created_at: string;
            /** Format: int64 */
            id: number;
            is_admin: boolean;
            username: string;
        };
        AuthResponse: {
            is_admin: boolean;
            token: string;
            username: string;
        };
        BreakdownRow: {
            /** Format: double */
            accuracy: number;
            /** Format: int64 */
            correct: number;
            label: string;
            /** Format: int64 */
            reviews: number;
        };
        /**
         * @description The canonical full-card shape: a `cards` row joined with its English
         *     translation and primary example sentence - exactly `CardFront` (next.rs)
         *     plus `CardBack` (check.rs), i.e. exactly what `CardPrompt` and
         *     `CardReveal` disclose between them minus the two fields that are
         *     review-flow state rather than properties of the card itself
         *     (`hanja_hint_words`, `hanja_hints` - both depend on the requesting user's
         *     review history, see `hanja_hints_for`).
         *
         *     Flattening the same two structs the review flow already produces, rather
         *     than hand-declaring their union a third time, is what keeps this
         *     in sync with them: `Card` used to be its own independently-declared
         *     20-field struct that merely happened to agree with `CardPrompt`/
         *     `CardReveal` - previously it was also independent of `admin::AdminCard`,
         *     which had the exact same problem in miniature (agreeing on 14 of its own
         *     fields) until both admin structs were unified into this one. Nothing
         *     enforced this wider agreement in the same way; the frontend's
         *     `toAdminCard`/`CARD_BACK_FIELDS` (lib/api.ts) had to hand-encode the
         *     front/back split from the outside, reconstructing in TypeScript what the
         *     Rust types could just express directly.
         *
         *     Shared verbatim by admin search (`admin::search_cards`) and edit
         *     (`admin::edit_card`). Not used by the review flow itself, which needs
         *     `CardPrompt`/`CardReveal` proper, extra per-user fields included -
         *     admin editing isn't gated by the same secrecy concerns, so it gets the
         *     whole row upfront.
         */
        Card: components["schemas"]["CardFront"] & components["schemas"]["CardBack"];
        /**
         * @description The card fields disclosed once an answer is graded, shared with the
         *     admin-editing shape - see `cards::Card`'s doc comment - and with
         *     `CardFront` (next.rs) for the withheld-until-graded relationship between
         *     the two. Split out from `CardReveal` (below) for the same reason
         *     `CardFront` was: so `Card` can flatten this struct instead of
         *     hand-declaring the same 6 fields a third time. Every field here would
         *     give the answer away if it shipped any earlier than `CardReveal` ships it.
         */
        CardBack: {
            alternatives: string[];
            definition?: string | null;
            hanja_eum?: string | null;
            sentence: string;
            target: string;
            word: string;
        };
        /**
         * @description The card fields visible before an answer is checked, shared with the
         *     admin-editing shape - see `cards::Card`'s doc comment - and with
         *     `CardBack` (check.rs) for the withheld half. Split out from `CardPrompt`
         *     (below) so `Card` can flatten this struct instead of hand-declaring the
         *     same 13 fields a third time: `Card` used to be its own standing struct
         *     that merely happened to agree with `CardPrompt`'s, the exact
         *     silent-drift risk `Card`'s doc comment already flags from its earlier
         *     history with the admin struct it replaced.
         *
         *     `definition` and the unsliced `sentence` are withheld too, even though
         *     neither is rendered by the review UI at all pre- or post-answer - they're
         *     authoring fields, not review-flow fields. `CardBack` carries them anyway,
         *     purely so an admin editing a card mid-review has a correct, non-blank
         *     baseline to save over.
         */
        CardFront: {
            /** Format: int64 */
            card_id: number;
            grade?: string | null;
            grammar_pattern?: string | null;
            hanja?: string | null;
            /**
             * Format: int64
             * @description KRDICT's `ParaWordNo` for this word, when it came from KRDICT. `None`
             *     for user-created custom cards, which have no upstream dictionary entry.
             */
            krdict_id?: number | null;
            origin_type?: string | null;
            pos?: string | null;
            /** @description The text after the blank. See `sentence_before`. */
            sentence_after: string;
            /**
             * @description `sentence`, sliced at `target`'s position: the text before the blank.
             *     Derived once here rather than by every renderer re-searching
             *     `sentence` for `target` - see `split_sentence`. The unsliced
             *     `sentence` and `target` itself are withheld; see `CardBack`.
             */
            sentence_before: string;
            sentence_translation: string;
            speech_level?: string | null;
            tense?: string | null;
            trans_dfn?: string | null;
            trans_word: string;
        };
        /**
         * @description Everything the client may see before it has attempted an answer:
         *     `CardFront` plus `hanja_hint_words`, the one field here that's genuinely
         *     review-flow-specific rather than a property of the card itself - it
         *     depends on the requesting user's review history (see `hanja_hints_for`),
         *     so it has no place on `CardFront`/`Card`. Served by `GET /api/cards/next`.
         */
        CardPrompt: components["schemas"]["CardFront"] & {
            /**
             * @description Hanja characters for the pre-answer hint span. The reading and each
             *     hint's gloss give the answer away - see `CardBack::hanja_eum` and
             *     `HanjaHint::trans_word`.
             */
            hanja_hint_words: string[];
        };
        /**
         * @description Disclosed only once `POST /api/cards/{id}/check` has graded an attempt:
         *     `CardBack` plus the two fields that are genuinely review-flow-specific
         *     rather than properties of the card itself - `hanja_hints` depends on the
         *     requesting user's review history (see `hanja_hints_for`), and
         *     `grammar_pattern_endings` belongs to the referenced `grammar_patterns`
         *     row, not this card - so neither has a place on `CardBack`/`Card`.
         */
        CardReveal: components["schemas"]["CardBack"] & {
            /**
             * @description The grammar pattern's possible conjugation endings - a property of
             *     the referenced `grammar_patterns` row, not of this card, but exactly
             *     as spoiling as `target` for any card that uses the pattern, so it
             *     travels with the reveal rather than in the pattern's public
             *     label/tooltip (see `list_field_values`, which admin/authoring
             *     surfaces still fetch endings from - that's a legitimately public use,
             *     picking a pattern rather than guessing one card's answer).
             */
            grammar_pattern_endings?: string | null;
            hanja_hints: components["schemas"]["HanjaHint"][];
        };
        CardTranslationExport: {
            language_tag: string;
            trans_dfn?: string | null;
            trans_word: string;
        };
        CheckRequest: {
            answer: string;
        };
        CheckResponse: components["schemas"]["CardReveal"] & {
            correct: boolean;
        };
        CommentRequest: {
            body: string;
        };
        CommentResponse: {
            /** Format: int64 */
            id: number;
        };
        CreateCustomCardRequest: {
            alternatives?: string[] | null;
            definition?: string | null;
            grade?: string | null;
            hanja?: string | null;
            hanja_eum?: string | null;
            origin_type?: string | null;
            pos?: string | null;
            sentence: string;
            sentence_translation: string;
            speech_level?: string | null;
            target: string;
            tense?: string | null;
            trans_dfn?: string | null;
            trans_word: string;
            word: string;
        };
        CreateCustomCardResponse: {
            /** Format: int64 */
            id: number;
            success: boolean;
        };
        CustomCard: {
            /**
             * @description Was missing here until this field was added: `CreateCustomCardRequest`,
             *     `UpdateCustomCardRequest`, and export/import's `SentenceExport` all
             *     accept/carry a card's alternative accepted answers, but this read
             *     shape - what `GET /api/custom-cards` and `GET /api/custom-cards/{id}`
             *     actually return - silently dropped them, so there was no way to see
             *     (or build an edit form around) alternatives you'd already set outside
             *     of a full data export. Same class of bug as `cards::Card` drifting
             *     from `CardPrompt`/`CardReveal` - independently hand-declared shapes
             *     of "the same card" agreeing on every field but one.
             */
            alternatives: string[];
            created_at: string;
            definition?: string | null;
            grade?: string | null;
            hanja?: string | null;
            hanja_eum?: string | null;
            /** Format: int64 */
            id: number;
            origin_type?: string | null;
            pos?: string | null;
            sentence: string;
            sentence_translation: string;
            speech_level?: string | null;
            target: string;
            tense?: string | null;
            trans_dfn?: string | null;
            trans_word: string;
            word: string;
        };
        CustomCardExport: {
            definition?: string | null;
            grade?: string | null;
            hanja?: string | null;
            hanja_eum?: string | null;
            origin_type?: string | null;
            pos?: string | null;
            sentences: components["schemas"]["SentenceExport"][];
            translations: components["schemas"]["CardTranslationExport"][];
            word: string;
        };
        DayHistory: {
            /** Format: int64 */
            correct: number;
            date: string;
            /** Format: int64 */
            percentage: number;
            /** Format: int64 */
            total: number;
        };
        EditCardResponse: {
            success: boolean;
        };
        /**
         * @description Schema-only mirror of the `{"error": "..."}` envelope every error
         *     response uses (built ad hoc via `serde_json::json!` in
         *     `AppError::into_response`, not actually constructed from this struct) -
         *     exists purely so `#[utoipa::path]` annotations have something to point
         *     error responses at.
         */
        ErrorResponse: {
            error: string;
        };
        ExportData: {
            custom_cards: components["schemas"]["CustomCardExport"][];
            exported_at: string;
            review_history: components["schemas"]["ReviewHistoryExport"][];
            settings: components["schemas"]["UserSettingsExport"];
            suspended_cards: number[];
            version: string;
        };
        /**
         * @description The six fields `FieldValues` can return values for, and the only legal
         *     values for `?fields=`. Wire values are snake_case (`grammar_pattern`,
         *     ...), matching the response's own field names - see
         *     `deserialize_field_list`.
         * @enum {string}
         */
        FieldName: "pos" | "origin_type" | "grade" | "speech_level" | "tense" | "grammar_pattern";
        FieldValue: {
            endings?: string | null;
            label: string;
            /** Format: int64 */
            rank?: number | null;
            slug: string;
            tooltip?: string | null;
        };
        FieldValues: {
            grade?: components["schemas"]["FieldValue"][] | null;
            grammar_pattern?: components["schemas"]["FieldValue"][] | null;
            origin_type?: components["schemas"]["FieldValue"][] | null;
            pos?: components["schemas"]["FieldValue"][] | null;
            speech_level?: components["schemas"]["FieldValue"][] | null;
            tense?: components["schemas"]["FieldValue"][] | null;
        };
        GenerateInvitesRequest: {
            /**
             * @description Defaults to 1 if omitted from the body, or if the body is omitted
             *     entirely (a POST with no `Content-Type` header at all).
             * @default 1
             */
            count: number;
        };
        GenerateInvitesResponse: {
            codes: components["schemas"]["GeneratedInvite"][];
        };
        GeneratedInvite: {
            code: string;
        };
        HanjaHint: {
            hanja: string;
            hanja_eum?: string | null;
            trans_word?: string | null;
        };
        HistoryBreakdownResponse: {
            by_origin: components["schemas"]["BreakdownRow"][];
            by_pos: components["schemas"]["BreakdownRow"][];
        };
        HistoryResponse: {
            /** @description All-time accuracy broken down by part-of-speech and by origin type. */
            breakdown: components["schemas"]["HistoryBreakdownResponse"];
            /** @description All-time aggregate + current FSRS state distribution + streaks. */
            summary: components["schemas"]["HistorySummary"];
            /** @description Rolling 5-day (today + 4 back) per-day review counts, for the small history chart. */
            timeseries: components["schemas"]["DayHistory"][];
        };
        HistorySummary: {
            /** Format: double */
            avg_reviews_per_day: number;
            /** Format: int64 */
            cards_learning: number;
            /** Format: int64 */
            cards_relearning: number;
            /** Format: int64 */
            cards_review: number;
            /** Format: int64 */
            cards_unseen: number;
            /** Format: int64 */
            current_streak: number;
            first_review_date?: string | null;
            /** Format: int64 */
            longest_streak: number;
            /** Format: double */
            total_accuracy: number;
            /** Format: int64 */
            total_cards_reviewed: number;
            /** Format: int64 */
            total_reviews: number;
        };
        ImportDataRequest: {
            data: components["schemas"]["ExportData"];
            overwrite: boolean;
        };
        ImportDataResponse: {
            message: string;
            stats: components["schemas"]["ImportStats"];
            success: boolean;
        };
        ImportStats: {
            card_states_derived: number;
            custom_cards_imported: number;
            reviews_imported: number;
            suspended_cards_imported: number;
        };
        InflectionHintExport: {
            speech_level?: string | null;
            tense?: string | null;
        };
        InviteCode: {
            code: string;
            created_at: string;
            used_at?: string | null;
            used_by_username?: string | null;
        };
        ListCustomCardsResponse: {
            cards: components["schemas"]["CustomCard"][];
        };
        ListInvitesResponse: {
            codes: components["schemas"]["InviteCode"][];
        };
        ListUsersResponse: {
            users: components["schemas"]["AdminUserSummary"][];
        };
        LoginRequest: {
            password: string;
            username: string;
        };
        NextCardEnvelope: {
            card?: null | components["schemas"]["NextCardResponse"];
            next_due_at?: string | null;
        };
        NextCardResponse: components["schemas"]["CardPrompt"] & {
            /** Format: double */
            difficulty?: number | null;
            /** Format: int64 */
            guess_count: number;
            /** Format: int64 */
            wrong_guess_count: number;
        };
        OptimizeFsrsResponse: {
            parameters: number[];
            review_count: number;
            success: boolean;
        };
        ReviewHistoryExport: {
            /** Format: int64 */
            card_id: number;
            /** Format: double */
            difficulty?: number | null;
            /** Format: double */
            elapsed_days?: number | null;
            rating: string;
            reviewed_at: string;
            /** Format: double */
            scheduled_days?: number | null;
            /** Format: double */
            stability?: number | null;
            state?: string | null;
        };
        ReviewResponse: {
            success: boolean;
        };
        SearchCardsResponse: {
            cards: components["schemas"]["Card"][];
        };
        SentenceExport: {
            alternatives?: string[];
            inflection_hint?: null | components["schemas"]["InflectionHintExport"];
            target: string;
            text: string;
            translation?: string | null;
        };
        SignupRequest: {
            invite_code: string;
            password: string;
            username: string;
        };
        StatsResponse: {
            /** Format: int64 */
            correct_today: number;
            /** Format: int64 */
            due_count: number;
            /** Format: int64 */
            new_count: number;
            /** Format: int64 */
            new_today_count: number;
            next_due_at?: string | null;
            /** Format: int64 */
            percentage?: number | null;
            /** Format: int64 */
            reviews_today: number;
        };
        SuppressedCard: {
            /** Format: int64 */
            card_id: number;
            grade?: string | null;
            pos?: string | null;
            sentence: string;
            sentence_translation: string;
            trans_word: string;
            word: string;
        };
        SuppressedCardsResponse: {
            cards: components["schemas"]["SuppressedCard"][];
        };
        /**
         * @description Partial card edit. Any field left out of the JSON body is untouched;
         *     nullable fields (`definition`, `pos`, `origin_type`, `hanja`, `hanja_eum`,
         *     `grade`, `trans_dfn`, `speech_level`, `tense`, `grammar_pattern`) can be
         *     explicitly set to `null` to clear the column — that's why they're typed
         *     `Option<Option<String>>` rather than `Option<String>`, so "omitted" and
         *     "explicit null" deserialize differently. Enum-backed fields are sent as
         *     slugs, resolved server-side to lookup-table row IDs.
         */
        UpdateCardRequest: {
            alternatives?: string[] | null;
            definition?: string | null;
            grade?: string | null;
            grammar_pattern?: string | null;
            hanja?: string | null;
            hanja_eum?: string | null;
            origin_type?: string | null;
            pos?: string | null;
            sentence?: string | null;
            sentence_translation?: string | null;
            speech_level?: string | null;
            target?: string | null;
            tense?: string | null;
            trans_dfn?: string | null;
            trans_word?: string | null;
            word?: string | null;
        };
        UpdateCustomCardRequest: {
            alternatives?: string[] | null;
            definition?: string | null;
            grade?: string | null;
            hanja?: string | null;
            hanja_eum?: string | null;
            origin_type?: string | null;
            pos?: string | null;
            sentence?: string | null;
            sentence_translation?: string | null;
            speech_level?: string | null;
            target?: string | null;
            tense?: string | null;
            trans_dfn?: string | null;
            trans_word?: string | null;
            word?: string | null;
        };
        UpdateCustomCardResponse: {
            success: boolean;
        };
        UpdateSettingsRequest: {
            /** Format: int64 */
            auto_progress_delay?: number | null;
            auto_progress_on_correct?: boolean | null;
            /** Format: int64 */
            daily_new_card_limit?: number | null;
            /** Format: int64 */
            day_boundary_hour?: number | null;
            /** Format: double */
            desired_retention?: number | null;
            history_colored_dots?: boolean | null;
            history_colorized_area?: boolean | null;
            history_threshold_lines?: boolean | null;
            /** Format: int64 */
            red_threshold?: number | null;
            show_percentage?: boolean | null;
            /** Format: int64 */
            yellow_threshold?: number | null;
        };
        UpdateSettingsResponse: {
            success: boolean;
        };
        UserProfile: {
            username: string;
        };
        UserSettings: components["schemas"]["UserSettingsCore"] & {
            /**
             * @description Whether the user has FSRS parameters fitted from their own review
             *     history, as opposed to library defaults - a presence flag, not the
             *     parameters themselves. See `UserSettingsExport::fsrs_parameters` for
             *     the portable form export/import actually needs; the two aren't the
             *     same field under different names, so this doesn't join `core`.
             */
            has_fsrs_parameters: boolean;
        };
        /**
         * @description The `user_settings` row proper - every field shared verbatim between the
         *     live API response (`UserSettings`, below) and data export/import
         *     (`export_import::UserSettingsExport`). Split out so both flatten this
         *     struct instead of hand-declaring the same 11 fields a second time: the
         *     export path used to be its own independently-declared struct that merely
         *     happened to agree with `UserSettings`, the same silent-drift risk
         *     `cards::Card` used to carry before it was unified from
         *     `CardFront`/`CardBack` (see its doc comment in cards/mod.rs) - a settings
         *     field added to the DB and to one of these two but not the other would
         *     silently vanish from export, or from the live API, with no compiler
         *     error either way. `sqlx::FromRow` lets both `get_settings` (below) and
         *     `export_import::get_user_settings` read a row straight into this shape
         *     too, rather than each hand-repeating the same 11 `row.get(...)` calls.
         */
        UserSettingsCore: {
            /** Format: int64 */
            auto_progress_delay: number;
            auto_progress_on_correct: boolean;
            /** Format: int64 */
            daily_new_card_limit: number;
            /** Format: int64 */
            day_boundary_hour: number;
            /** Format: double */
            desired_retention: number;
            history_colored_dots: boolean;
            history_colorized_area: boolean;
            history_threshold_lines: boolean;
            /** Format: int64 */
            red_threshold: number;
            show_percentage: boolean;
            /** Format: int64 */
            yellow_threshold: number;
        };
        UserSettingsExport: components["schemas"]["UserSettingsCore"] & {
            fsrs_parameters?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_cards: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cards matching a substring search over sentence targets, or an exact card id match (capped at 50) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchCardsResponse"];
                };
            };
            /** @description Malformed query string */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Valid JWT but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    edit_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCardRequest"];
            };
        };
        responses: {
            /** @description Card updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditCardResponse"];
                };
            };
            /** @description Target word doesn't appear in the sentence */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Valid JWT but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Card doesn't exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_invites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All invite codes, used and unused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListInvitesResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Valid JWT but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generate_invites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Optional; omit the body entirely (or omit `count` within it) to generate 1 code */
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["GenerateInvitesRequest"];
            };
        };
        responses: {
            /** @description Invite codes generated (capped at 100 per request) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateInvitesResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Valid JWT but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invite code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite code deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Valid JWT but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Code doesn't exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: {
                /** @description Exact username match. Omit to list every user. */
                username?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All users, or the one matching ?username= exactly */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUsersResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Valid JWT but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid/used invite code, or malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Username already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_field_values: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated subset of fields to return (e.g. `fields=pos,tense`).
                 *     Omit entirely to get all six.
                 */
                fields?: components["schemas"]["FieldName"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lookup-table values for dropdowns/enum displays. Fields not requested via `?fields=` are omitted entirely rather than sent empty. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldValues"];
                };
            };
            /** @description Unknown name in `?fields=` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Time series, all-time summary + streaks, and POS/origin accuracy breakdown, run concurrently */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_next_card: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated card ids to exclude from the result. The frontend's
                 *     prefetch sends exactly one (the card currently on screen); the
                 *     hwaiting-agent CLI sends its whole local set of already-claimed
                 *     cards, so that concurrent agent processes don't get handed a card
                 *     someone else already has. `serde_urlencoded` (what axum's `Query`
                 *     extractor uses) has no support for repeated-key arrays, hence the
                 *     comma-joined string instead of `exclude=1&exclude=2`. `explode =
                 *     false` records that in the schema too, so generated clients send
                 *     `exclude=1,2,3` (style: form, explode: false) instead of the
                 *     OpenAPI-default repeated-key form this endpoint can't parse.
                 */
                exclude?: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next due/new card, or null if none due */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextCardEnvelope"];
                };
            };
            /** @description Malformed query string */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    optimize_fsrs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FSRS parameters optimized from full review history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizeFsrsResponse"];
                };
            };
            /** @description No/insufficient review history to optimize from */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reset_fsrs_parameters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FSRS parameters reset to library defaults */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status-bar summary stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_suppressed_cards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All suspended cards for the user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuppressedCardsResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    check_answer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Answer graded, FSRS state updated, secret fields revealed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Card doesn't exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    comment_on_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentRequest"];
            };
        };
        responses: {
            /** @description Comment recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    suppress_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card suspended from review rotation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    unsuppress_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card un-suspended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_custom_cards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All custom cards owned by the caller */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCustomCardsResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_custom_card: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomCardRequest"];
            };
        };
        responses: {
            /** @description Custom card created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCustomCardResponse"];
                };
            };
            /** @description Empty required field or target not in sentence */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_custom_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Custom card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single custom card */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomCard"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found, or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_custom_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Custom card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom card deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found, or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_custom_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Custom card ID */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomCardRequest"];
            };
        };
        responses: {
            /** @description Custom card updated (partial update) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateCustomCardResponse"];
                };
            };
            /** @description Empty field or target not in sentence */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found, or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    export_data: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full data export: settings, review history, suspended cards, custom cards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportData"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    import_data: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportDataRequest"];
            };
        };
        responses: {
            /** @description Data imported (card_states derived from imported review_history) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDataResponse"];
                };
            };
            /** @description Unsupported export version or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user's profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user settings (row lazily created on first access) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description Settings updated (partial update, only provided fields written) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateSettingsResponse"];
                };
            };
            /** @description Out-of-range value or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing/invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
